config/routes.rb
Rails.application.routes.draw do
  get 'trainers/index'

  get 'trainers/edit'

  get 'trainers/show'

  get 'trainers/new'

  get 'trainers/form'

  get 'tokimons/index'

  get 'tokimons/edit'

  get 'tokimons/show'

  get 'tokimons/new'

  get 'tokimons/form'
  
  get 'tokimons/display' 
  #match	':controller(/:action(/:id))',	:via	=>	:get
  #match	':controller(/:action(/:id))',	:via	=>	:post
  resources :tokimons
  resources :trainers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'trainers#index'
  
  #create display pages


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tokimon.rb
class Tokimon < ApplicationRecord
  belongs_to :trainer
  
  validates :tkname, presence: true
  validates :weight, presence: true
  validates :height, presence: true
  validates :fly, presence: true
  validates :fight, presence: true
  validates :fire, presence: true
  validates :water, presence: true
  validates :electric, presence: true
  validates :ice, presence: true
  
  def total
    self.fly + self.fight + self.fire + self.water + self.electric + self.ice
  end


  
end

app/models/trainer.rb
class Trainer < ApplicationRecord
    has_many :tokimons
    
    validates :trname, presence: true
    validates :gender, presence: true
    validates :country, presence: true

    def level
        (self.tokimons.length/3).round
    end
    
  
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tokimons_controller.rb
class TokimonsController < ApplicationController
before_action :set_tokimon, only: [:show, :edit, :update, :destroy]

  # GET /tokimons
  # GET /tokimons.json
  def index
    @tokimons = Tokimon.all
  end

  # GET /tokimons/1
  # GET /tokimons/1.json
  def show
  end

  # GET /tokimons/1/edit
  def edit
  end
  
  def display
    @tokimons = Tokimon.all
  end
  


  # GET /tokimons/new
  def new
     @tokimon = Tokimon.new
  end

  def form
  end

  # POST /tokimons
  # POST /tokimons.json
  def create
    
    
    @tokimon = Tokimon.new(tokimon_params)

    respond_to do |format|
      if @tokimon.save
        format.html { redirect_to @tokimon, notice: 'Tokimon was successfully created.' }
        format.json { render :show, status: :created, location: @tokimon }
      else
        format.html { render :new }
        format.json { render json: @tokimon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tokimons/1
  # PATCH/PUT /tokimons/1.json
  def update
    respond_to do |format|
      if @tokimon.update(tokimon_params)
        format.html { redirect_to @tokimon, notice: 'Tokimon was successfully updated.' }
        format.json { render :show, status: :ok, location: @tokimon }
      else
        format.html { render :edit }
        format.json { render json: @tokimon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tokimons/1
  # DELETE /tokimons/1.json
  def destroy
    @tokimon.destroy
    respond_to do |format|
      format.html { redirect_to tokimons_url, notice: 'Tokimon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tokimon
      @tokimon = Tokimon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tokimon_params
      params.require(:tokimon).permit(:tkname, :weight, :height, :fly, :fight, :fire, :water, :electric, :ice, :total, :trainer_id)
    end
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  before_action :set_trainer, only: [:show, :edit, :update, :destroy]

  # GET /trainers
  # GET /trainers.json
  def index
    @trainers = Trainer.all
  end

  # GET /trainers/1
  # GET /trainers/1.json
  def show
  end

  # GET /trainers/new
  def new
    @trainer = Trainer.new
  end

  # GET /trainers/1/edit
  def edit
  end

  # POST /trainers
  # POST /trainers.json
  def create
    @trainer = Trainer.new(trainer_params)

    respond_to do |format|
      if @trainer.save
        format.html { redirect_to @trainer, notice: 'Trainer was successfully created.' }
        format.json { render :show, status: :created, location: @trainer }
      else
        format.html { render :new }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainers/1
  # PATCH/PUT /trainers/1.json
  def update
    respond_to do |format|
      if @trainer.update(trainer_params)
        format.html { redirect_to @trainer, notice: 'Trainer was successfully updated.' }
        format.json { render :show, status: :ok, location: @trainer }
      else
        format.html { render :edit }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainers/1
  # DELETE /trainers/1.json
  def destroy
    @trainer.destroy
    respond_to do |format|
      format.html { redirect_to trainers_url, notice: 'Trainer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trainer
      @trainer = Trainer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trainer_params
      params.require(:trainer).permit(:trname, :level, :gender, :country, :motto, :trid, :team)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tokimons_helper.rb
module TokimonsHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TokimonApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tokimons/_form.html.erb
<%= form_for(tokimon) do |f| %>
  <% if tokimon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tokimon.errors.count, "error") %> prohibited this tokimon from being saved:</h2>

      <ul>
      <% tokimon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label("Tokimon Name") %>
    <%= f.text_field :tkname %>
  </div>

  <div class="field">
    <%= f.label("Weight in Pounds") %>
    <%= f.number_field :weight, :min => 0 %>
  </div>

  <div class="field">
    <%= f.label("Height in CM") %>
    <%= f.number_field :height, :min => 0 %>
  </div>

  <div class="field">
    <%= f.label :fly %>
    <%= f.number_field :fly, :min => 0, :max => 100 %>
  </div>

  <div class="field">
    <%= f.label :fight %>
    <%= f.number_field :fight, :min => 0, :max => 100 %>
  </div>

  <div class="field">
    <%= f.label :fire %>
    <%= f.number_field :fire, :min => 0, :max => 100 %>
  </div>

  <div class="field">
    <%= f.label :water %>
    <%= f.number_field :water, :min => 0, :max => 100 %>
  </div>

  <div class="field">
    <%= f.label :electric %>
    <%= f.number_field :electric, :min => 0, :max => 100 %>
  </div>

  <div class="field">
    <%= f.label :ice %>
    <%= f.number_field :ice, :min => 0, :max => 100 %>
  </div>

  <div class="field">
    <%= f.label :total %>
    
  </div>
  
    <div class="field">
    <%= f.label :trainer_id %><br>
    <%= f.collection_select( :trainer_id, Trainer.all, :id, :trname, {:include_blank => true} )%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tokimons/display.html.erb
<h1>Displaying Tokimon as relative size</h1>

<% @tokimons.each do |tokimon| %>
  <div class="div_box" style="width:<%=tokimon.weight%>px; height:<%=tokimon.height%>px; color: black">
    <p class="s_box"><%= tokimon.tkname %></p>
    <p class="s_box"><%= tokimon.total  %></p>
    
  </div>
<% end %>




<br>
<%= link_to 'Back', tokimons_path %>

app/views/tokimons/edit.html.erb
<h1>Editing Tokimon</h1>

<%= render 'form', tokimon: @tokimon %>

<%= link_to 'Show', @tokimon %> |
<%= link_to 'Back', tokimons_path %>

app/views/tokimons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tokimons</h1>

<table>
  <thead>
    <tr>
      <th>Tokimon name</th>
      <th>Weight</th>
      <th>Height</th>
      <th>Fly</th>
      <th>Fight</th>
      <th>Fire</th>
      <th>Water</th>
      <th>Electric</th>
      <th>Ice</th>
      <th>Total</th>
      <th>Trainer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tokimons.each do |tokimon| %>
      <tr class="<%= cycle('odd', 'even') %>">
        <td><%= tokimon.tkname %></td>
        <td><%= tokimon.weight %></td>
        <td><%= tokimon.height %></td>
        <td><%= tokimon.fly %></td>
        <td><%= tokimon.fight %></td>
        <td><%= tokimon.fire %></td>
        <td><%= tokimon.water %></td>
        <td><%= tokimon.electric %></td>
        <td><%= tokimon.ice %></td>
        <td><%= tokimon.total %></td>
        <td><%= tokimon.trainer.trname %></td>
        <td><%= link_to 'Show', tokimon %></td>
        <td><%= link_to 'Edit', edit_tokimon_path(tokimon) %></td>
        <td><%= link_to 'Destroy', tokimon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tokimon', new_tokimon_path %>
<%= link_to 'Trainers', trainers_path %>

<br>
<br>


<%= link_to 'Display Relative', tokimons_display_path %>

app/views/tokimons/new.html.erb
<h1>Tokimons#new</h1>
<p>Find me in app/views/tokimons/new.html.erb</p>


<%= render 'form', tokimon: @tokimon %>

<%= link_to 'Back', tokimons_path %>

app/views/tokimons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tokimon name:</strong>
  <%= @tokimon.tkname %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @tokimon.weight %>
</p>

<p>
  <strong>Height:</strong>
  <%= @tokimon.height %>
</p>

<p>
  <strong>Fly:</strong>
  <%= @tokimon.fly %>
</p>

<p>
  <strong>Fight:</strong>
  <%= @tokimon.fight %>
</p>

<p>
  <strong>Fire:</strong>
  <%= @tokimon.fire %>
</p>

<p>
  <strong>Water:</strong>
  <%= @tokimon.water %>
</p>

<p>
  <strong>Electric:</strong>
  <%= @tokimon.electric %>
</p>

<p>
  <strong>Ice:</strong>
  <%= @tokimon.ice %>
</p>

<p>
  <strong>Total:</strong>
  <%= @tokimon.total %>
</p>

<p>
  <strong>Belongs to Trainer:</strong>
  <%= @tokimon.trainer.trname %>
</p>

<%= link_to 'Edit', edit_tokimon_path(@tokimon) %> |
<%= link_to 'Back', tokimons_path %>  |
<%= link_to 'Visit Trainer Page', @tokimon.trainer %>

app/views/trainers/_form.html.erb
<%= form_for(trainer) do |f| %>
  <% if trainer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trainer.errors.count, "error") %> prohibited this trainer from being saved:</h2>

      <ul>
      <% trainer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label("Trainer Name") %>
    <%= f.text_field :trname %>
  </div>

  <div class="field">
    <%= f.label :level %>
    
  </div>

  <div class="field">
    <%= f.label :gender %>
    <%= f.select :gender, ["Male", "Female", "Other"] %>
  </div>

  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>

  <div class="field">
    <%= f.label :motto %>
    <%= f.text_field :motto %>
  </div>

  <div class="field">
    <%= f.label :id %>
    
  </div>
  
  <div class="field">
    <%= f.label :team %>
    <%= f.select :team, ["red", "blue", "yellow"] %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trainers/edit.html.erb
<h1>Editing Trainer</h1>

<%= render 'form', trainer: @trainer %>

<%= link_to 'Show', @trainer %> |
<%= link_to 'Back', trainers_path %>

app/views/trainers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trainers</h1>

<table>
  <thead>
    <tr>
      <th>Trname</th>
      <th>Level</th>
      <th>Gender</th>
      <th>Country</th>
      <th>Motto</th>
      <th>Id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trainers.each do |trainer| %>
      <tr class="<%= cycle('odd', 'even') %>">
        <td><%= trainer.trname %></td>
        <td><%= trainer.level %></td>
        <td><%= trainer.gender %></td>
        <td><%= trainer.country %></td>
        <td><%= trainer.motto %></td>
        <td><%= trainer.id %></td>
        <td><%= link_to 'Show', trainer %></td>
        <td><%= link_to 'Edit', edit_trainer_path(trainer) %></td>
        <td><%= link_to 'Destroy', trainer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trainer', new_trainer_path %>
<%= link_to 'List of Tokimons', tokimons_path %>

app/views/trainers/new.html.erb
<h1>New Trainer</h1>

<%= render 'form', trainer: @trainer %>

<%= link_to 'Back', trainers_path %>

app/views/trainers/show.html.erb
<p id="notice"><%= notice %></p>

<p style= "color: <%= @trainer.team %>" >
  <strong>Trname:</strong>
  <%= @trainer.trname %>
</p>

<p>
  <strong>Level:</strong>
  <%= @trainer.level %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @trainer.gender %>
</p>

<p>
  <strong>Country:</strong>
  <%= @trainer.country %>
</p>

<p>
  <strong>Motto:</strong>
  <%= @trainer.motto %>
</p>

<p>
  <strong>Id:</strong>
  <%= @trainer.id %>
</p>

<h3>Related Tokimon</h3>

<ul>
  <% @trainer.tokimons.each do |tokimon| %>
    <li><%= tokimon.tkname %> <%= link_to "Details", tokimon_path(tokimon) %></li>
  <% end %>
</ul>



<% @trainer.tokimons.each do |tokimon| %>
    <div class="div_box" style="width:<%=tokimon.weight%>px; height:<%=tokimon.height%>px; color: black">
        <p class="s_box"><%= tokimon.tkname %></p>
        <p class="s_box">Abilities Total: <%= tokimon.total  %></p>
    </div>
<% end %>
    
<br>


<%= link_to 'Edit', edit_trainer_path(@trainer) %> |
<%= link_to 'Back', trainers_path %>